exclude:
- /MGen/configs/.*
- /MGen/configs_old/GenCF1/.*
- /MGen/example_config_for_range.pl
- /MGen/instruments/.*
- /MGen/midifile/.*
- /MGen/portmidi/.*
- /MGen/readerwriterqueue/.*
- /MGen/rtmidi/.*
- /MGenTest/MGenTest.rc
- /MGenTest/MGenTest.vcxproj
- /MGenTest/MGenTest.vcxproj.filters
- /MGenTest/ReadMe.txt
component_depth: 1
languages:
- name: cpp
  test:
    include:
      - /MGenTest/.*
- perl
