version: 1.0.{build}
image: Visual Studio 2017
configuration:
- Release
- Debug
build:
  verbosity: minimal
test: off
on_success:
- cmd: >-
    appveyor AddMessage start

    "%APPVEYOR_BUILD_FOLDER%\x64\Release\MGen"

    appveyor AddMessage stop
