version: 1.0.{build}
image: Visual Studio 2017
platform:
  - x86
  - x64
configuration: 
  - Release
  - Debug
build:
  verbosity: minimal
test: off
on_success:
- cmd: >-
    cd "%APPVEYOR_BUILD_FOLDER%\Mgen\autotest"

    test
